In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

In [23]:
results_db = pd.read_csv("../data/train_test_data.csv")

In [3]:
results_db = results_db[['favorite', 'underdog', 'spread_favorite', 'season_total_points_for _favorite', 'season_total_points_against_favorite', 'season_total_points_for _underdog', 'season_total_points_against_underdog', 'home_win', 'favorite_win']]

In [4]:
results_db = results_db.rename(columns={"season_total_points_for _favorite": "season_total_points_favorite", "season_total_points_for _underdog": "season_total_points_underdog"})

In [5]:
results_db.head()

,favorite,underdog,spread_favorite,season_total_points_favorite,season_total_points_against_favorite,season_total_points_underdog,season_total_points_against_underdog,home_win,favorite_win
0,NE,PIT,-7.0,28,21,21,28,1,1
1,ARI,NO,-2.5,31,19,19,31,1,1
2,IND,BUF,-1.0,14,27,27,14,1,0
3,GB,CHI,-6.5,31,23,23,31,0,1
4,DAL,NYG,-7.0,27,26,26,27,1,1

In [36]:
team_mapping = {}

for idx, row in results_db.iterrows():
    fave_name = row["favorite"]
    if fave_name not in team_mapping:
        team_mapping[fave_name] = len(team_mapping)
    under_name = row["underdog"]
    if under_name not in team_mapping:
        team_mapping[under_name] = len(team_mapping)

print(team_mapping)

{'NE': 0, 'PIT': 1, 'ARI': 2, 'NO': 3, 'IND': 4, 'BUF': 5, 'GB': 6, 'CHI': 7, 'DAL': 8, 'NYG': 9, 'DEN': 10, 'BAL': 11, 'KC': 12, 'HOU': 13, 'CAR': 14, 'JAX': 15, 'NYJ': 16, 'CLE': 17, 'OAK': 18, 'CIN': 19, 'LAC': 20, 'DET': 21, 'SEA': 22, 'LAR': 23, 'TB': 24, 'TEN': 25, 'MIA': 26, 'WAS': 27, 'PHI': 28, 'ATL': 29, 'MIN': 30, 'SF': 31}

In [37]:
for name in team_mapping:
    results_db.replace(to_replace=name, value=team_mapping[name], inplace=True)
results_db.head()

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,...,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog,favorite_win
0,9/10/2015,2015,1,0,28,21,1,-7.0,1,0,...,1,28,21,28,21,21,28,1,0,1
1,9/13/2015,2015,1,2,31,19,3,-2.5,1,0,...,3,31,19,31,19,19,31,1,0,1
2,9/13/2015,2015,1,5,27,14,4,-1.0,1,0,...,5,14,27,14,27,27,14,0,1,0
3,9/13/2015,2015,1,7,23,31,6,-6.5,0,1,...,7,31,23,31,23,23,31,1,0,1
4,9/13/2015,2015,1,8,27,26,9,-7.0,1,0,...,9,27,26,27,26,26,27,1,0,1

In [38]:
#split data into training and testing

In [39]:
y=results_db["favorite_win"].values.reshape(-1,1)
X=results_db.drop(columns="favorite_win")
X.shape

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [40]:
#create a logical regression model

In [20]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

classifier.fit(X_train, y_train)

C:\Users\Mark\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mark\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [21]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.7701005025125628
Testing Data Score: 0.7819548872180451

In [22]:
#make predictions

In [28]:
predictions = classifier.predict(X_test)
y_list = [x[0] for x in y_test]
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_list[:10]}")

First 10 Predictions:   [1 1 1 1 1 1 1 1 1 1]
First 10 Actual labels: [1, 1, 0, 0, 1, 1, 1, 1, 1, 0]

In [29]:
pd.DataFrame({"Prediction": predictions, "Actual": y_list}).reset_index(drop=True)

     Prediction  Actual
0             1       1
1             1       1
2             1       0
3             1       0
4             1       1
5             1       1
6             1       1
7             1       1
8             1       1
9             1       0
10            1       1
11            1       1
12            1       1
13            0       0
14            1       1
15            1       1
16            1       1
17            1       1
18            1       1
19            1       1
20            1       1
21            1       1
22            1       1
23            1       1
24            1       1
25            1       1
26            1       1
27            1       1
28            1       1
29            1       1
..          ...     ...
236           1       1
237           1       1
238           1       1
239           1       1
240           1       1
241           1       0
242           1       1
243           0       1
244           0       0
245           1       1
246           1       1
247           1       1
248           0       0
249           1       1
250           1       1
251           0       0
252           1       1
253           0       0
254           0       0
255           1       1
256           0       0
257           0       0
258           1       1
259           0       0
260           0       0
261           1       1
262           0       0
263           1       1
264           0       0
265           1       1

[266 rows x 2 columns]

In [33]:
#Compare results to KNN model
#Dependencies


from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [35]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScater model and fit it to the training data

X_scaler = StandardScaler().fit(X_train.reshape(-1, 1))

AttributeError: 'DataFrame' object has no attribute 'reshape'