In [1]:
import pandas as pd
import numpy as np

In [2]:
results_db = pd.read_csv("../data/game_data.csv")
results_db.tail(10)

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,favorite,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog
1052,1/5/2019,2018,18,HOU,7,21,IND,-2.0,0,1,HOU,IND,0,0,0,0,0,0,0,0
1053,1/6/2019,2018,18,BAL,17,23,LAC,-3.0,0,1,BAL,LAC,0,0,0,0,0,0,0,0
1054,1/6/2019,2018,18,CHI,15,16,PHI,-6.5,0,1,CHI,PHI,0,0,0,0,0,0,0,0
1055,1/12/2019,2018,19,KC,31,13,IND,-4.0,1,0,KC,IND,0,0,0,0,0,0,0,0
1056,1/12/2019,2018,19,LAR,30,22,DAL,-7.5,1,0,LAR,DAL,0,0,0,0,0,0,0,0
1057,1/13/2019,2018,19,NE,41,28,LAC,-3.5,1,0,NE,LAC,0,0,501,0,0,0,0,0
1058,1/13/2019,2018,19,NO,20,14,PHI,-8.5,1,0,NO,PHI,0,476,0,0,0,0,0,0
1059,1/20/2019,2018,20,KC,31,37,NE,-3.0,0,1,KC,NE,0,0,0,0,538,0,0,0
1060,1/20/2019,2018,20,NO,23,26,LAR,-3.0,0,1,NO,LAR,0,499,0,0,0,0,0,0
1061,2/3/2019,2018,21,LAR,3,13,NE,-2.0,0,1,NE,LAR,0,0,551,0,0,0,0,0

In [3]:
def underdog_score(game):
    if game['underdog'] == game['team_home']:
        return game['score_home']
    else:
        return game['score_away']

results_db['score_underdog'] = results_db.apply(underdog_score, axis=1)

In [4]:
def favorite_score(game):
    if game['favorite'] == game['team_home']:
        return game['score_home']
    else:
        return game['score_away']

results_db['score_favorite'] = results_db.apply(favorite_score, axis=1)

In [5]:
results_db["favorite_win"] = [1 if x>y else 0 for x,y in zip(results_db['score_favorite'], results_db['score_underdog'])]

In [6]:
season_2015 = results_db['schedule_season'] == 2015
season_2016 = results_db['schedule_season'] == 2016
season_2017 = results_db['schedule_season'] == 2017
season_2018 = results_db['schedule_season'] == 2018

In [7]:
season_2015_db = results_db[season_2015]
season_2016_db = results_db[season_2016]
season_2017_db = results_db[season_2017]
season_2018_db = results_db[season_2018]

In [75]:
season_2015_db.tail()

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,...,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog,favorite_win
259,1/17/2016,2015,19,CAR,31,24,SEA,-2.5,1,0,...,SEA,31,24,531,332,457,317,0,0,1
260,1/17/2016,2015,19,DEN,23,16,PIT,-7.5,1,0,...,PIT,23,16,378,312,447,342,0,0,1
261,1/24/2016,2015,20,CAR,49,15,ARI,-3.0,1,0,...,ARI,49,15,580,347,530,382,0,0,1
262,1/24/2016,2015,20,DEN,20,18,NE,-3.0,1,0,...,DEN,18,20,510,355,398,330,0,0,0
263,2/7/2016,2015,21,DEN,24,10,CAR,-4.5,1,0,...,DEN,10,24,590,371,422,340,0,0,0

In [69]:
scores = {
    "CAR":0,
    "TB":0,
    'ATL':0,
    'NO':0,
    'IND':0,
    'HOU':0,
    'JAX':0,
    'TEN':0,
    'WAS':0,
    'DAL':0,
    'PHI':0,
    'NYG':0,
    'NE':0,
    'NYJ':0,
    'MIA':0,
    'BUF':0,
    'GB':0,
    'CHI':0,
    'MIN':0,
    'DET':0,
    'BAL':0,
    'PIT':0,
    'CLE':0,
    'CIN':0,
    'SF':0,
    'SEA':0,
    'ARI':0,
    'LAR':0,
    'LAC':0,
    'KC':0,
    'DEN':0,
    'OAK':0
}

In [73]:
print(scores)

{'CAR': 590, 'TB': 342, 'ATL': 300, 'NO': 408, 'IND': 333, 'HOU': 339, 'JAX': 376, 'TEN': 299, 'WAS': 406, 'DAL': 247, 'PHI': 377, 'NYG': 420, 'NE': 510, 'NYJ': 387, 'MIA': 310, 'BUF': 379, 'GB': 393, 'CHI': 335, 'MIN': 361, 'DET': 358, 'BAL': 328, 'PIT': 447, 'CLE': 278, 'CIN': 419, 'SF': 238, 'SEA': 457, 'ARI': 530, 'LAR': 280, 'LAC': 320, 'KC': 455, 'DEN': 422, 'OAK': 359}

In [71]:
week_score_2015 = []
favs_2015 = []
dogs_2015 = []

In [72]:
current_week = 1
#current_year = 2015
for game in season_2015_db.iterrows():
    #print(game[1])
    if game[1][2] != current_week:
        #print(game[1][4])
        week_score_2015.append(scores.copy())
        current_week = game[1][2]
    scores[game[1][3]]+=game[1][4]
    scores[game[1][6]]+=game[1][5]
    if game[1][2] == 21:
        week_score_2015.append(scores.copy())
        break  

print(len(week_score_2015))

21

In [74]:
print(week_score_2015)

[{'CAR': 20, 'TB': 14, 'ATL': 26, 'NO': 19, 'IND': 14, 'HOU': 20, 'JAX': 9, 'TEN': 42, 'WAS': 10, 'DAL': 27, 'PHI': 24, 'NYG': 26, 'NE': 28, 'NYJ': 31, 'MIA': 17, 'BUF': 27, 'GB': 31, 'CHI': 23, 'MIN': 3, 'DET': 28, 'BAL': 13, 'PIT': 21, 'CLE': 10, 'CIN': 33, 'SF': 20, 'SEA': 31, 'ARI': 31, 'LAR': 34, 'LAC': 33, 'KC': 27, 'DEN': 19, 'OAK': 13}, {'CAR': 44, 'TB': 40, 'ATL': 50, 'NO': 38, 'IND': 21, 'HOU': 37, 'JAX': 32, 'TEN': 56, 'WAS': 34, 'DAL': 47, 'PHI': 34, 'NYG': 46, 'NE': 68, 'NYJ': 51, 'MIA': 37, 'BUF': 59, 'GB': 58, 'CHI': 46, 'MIN': 29, 'DET': 44, 'BAL': 46, 'PIT': 64, 'CLE': 38, 'CIN': 57, 'SF': 38, 'SEA': 48, 'ARI': 79, 'LAR': 44, 'LAC': 52, 'KC': 51, 'DEN': 50, 'OAK': 50}, {'CAR': 71, 'TB': 49, 'ATL': 50, 'NO': 60, 'IND': 56, 'HOU': 56, 'JAX': 49, 'TEN': 89, 'WAS': 55, 'DAL': 47, 'PHI': 58, 'NYG': 78, 'NE': 119, 'NYJ': 68, 'MIA': 51, 'BUF': 100, 'GB': 96, 'CHI': 46, 'MIN': 60, 'DET': 56, 'BAL': 70, 'PIT': 76, 'CLE': 58, 'CIN': 85, 'SF': 45, 'SEA': 74, 'ARI': 126, 'LAR': 50, 'LAC': 66, 'KC': 79, 'DEN': 74, 'OAK': 77}, {'CAR': 108, 'TB': 72, 'ATL': 98, 'NO': 86, 'IND': 72, 'HOU': 77, 'JAX': 62, 'TEN': 89, 'WAS': 78, 'DAL': 67, 'PHI': 78, 'NYG': 102, 'NE': 119, 'NYJ': 95, 'MIA': 65, 'BUF': 110, 'GB': 113, 'CHI': 68, 'MIN': 80, 'DET': 66, 'BAL': 93, 'PIT': 96, 'CLE': 85, 'CIN': 121, 'SF': 48, 'SEA': 87, 'ARI': 148, 'LAR': 74, 'LAC': 96, 'KC': 100, 'DEN': 97, 'OAK': 97}, {'CAR': 108, 'TB': 110, 'ATL': 123, 'NO': 103, 'IND': 99, 'HOU': 97, 'JAX': 93, 'TEN': 102, 'WAS': 97, 'DAL': 73, 'PHI': 117, 'NYG': 132, 'NE': 149, 'NYJ': 95, 'MIA': 65, 'BUF': 124, 'GB': 137, 'CHI': 86, 'MIN': 80, 'DET': 83, 'BAL': 123, 'PIT': 120, 'CLE': 118, 'CIN': 148, 'SF': 75, 'SEA': 111, 'ARI': 190, 'LAR': 84, 'LAC': 116, 'KC': 117, 'DEN': 113, 'OAK': 107}, {'CAR': 135, 'TB': 110, 'ATL': 144, 'NO': 134, 'IND': 126, 'HOU': 128, 'JAX': 113, 'TEN': 112, 'WAS': 117, 'DAL': 73, 'PHI': 144, 'NYG': 139, 'NE': 183, 'NYJ': 129, 'MIA': 103, 'BUF': 145, 'GB': 164, 'CHI': 120, 'MIN': 96, 'DET': 120, 'BAL': 143, 'PIT': 145, 'CLE': 141, 'CIN': 182, 'SF': 100, 'SEA': 134, 'ARI': 203, 'LAR': 84, 'LAC': 136, 'KC': 127, 'DEN': 139, 'OAK': 107}, {'CAR': 162, 'TB': 140, 'ATL': 154, 'NO': 161, 'IND': 147, 'HOU': 154, 'JAX': 147, 'TEN': 119, 'WAS': 148, 'DAL': 93, 'PHI': 160, 'NYG': 166, 'NE': 213, 'NYJ': 152, 'MIA': 147, 'BUF': 176, 'GB': 164, 'CHI': 120, 'MIN': 124, 'DET': 139, 'BAL': 161, 'PIT': 158, 'CLE': 147, 'CIN': 182, 'SF': 103, 'SEA': 154, 'ARI': 229, 'LAR': 108, 'LAC': 165, 'KC': 150, 'DEN': 139, 'OAK': 144}, {'CAR': 191, 'TB': 163, 'ATL': 174, 'NO': 213, 'IND': 173, 'HOU': 174, 'JAX': 147, 'TEN': 125, 'WAS': 148, 'DAL': 105, 'PHI': 160, 'NYG': 215, 'NE': 249, 'NYJ': 172, 'MIA': 154, 'BUF': 176, 'GB': 174, 'CHI': 140, 'MIN': 147, 'DET': 149, 'BAL': 190, 'PIT': 158, 'CLE': 167, 'CIN': 182, 'SF': 109, 'SEA': 167, 'ARI': 263, 'LAR': 135, 'LAC': 191, 'KC': 195, 'DEN': 168, 'OAK': 178}, {'CAR': 228, 'TB': 181, 'ATL': 190, 'NO': 241, 'IND': 200, 'HOU': 174, 'JAX': 170, 'TEN': 159, 'WAS': 158, 'DAL': 132, 'PHI': 193, 'NYG': 247, 'NE': 276, 'NYJ': 200, 'MIA': 171, 'BUF': 209, 'GB': 203, 'CHI': 162, 'MIN': 168, 'DET': 149, 'BAL': 190, 'PIT': 196, 'CLE': 177, 'CIN': 213, 'SF': 126, 'SEA': 167, 'ARI': 263, 'LAR': 153, 'LAC': 210, 'KC': 195, 'DEN': 192, 'OAK': 213}, {'CAR': 255, 'TB': 191, 'ATL': 190, 'NO': 255, 'IND': 200, 'HOU': 184, 'JAX': 192, 'TEN': 169, 'WAS': 205, 'DAL': 138, 'PHI': 212, 'NYG': 273, 'NE': 303, 'NYJ': 217, 'MIA': 191, 'BUF': 231, 'GB': 219, 'CHI': 199, 'MIN': 198, 'DET': 167, 'BAL': 210, 'PIT': 226, 'CLE': 186, 'CIN': 219, 'SF': 126, 'SEA': 199, 'ARI': 302, 'LAR': 166, 'LAC': 210, 'KC': 224, 'DEN': 205, 'OAK': 227}, {'CAR': 299, 'TB': 236, 'ATL': 211, 'NO': 255, 'IND': 224, 'HOU': 208, 'JAX': 211, 'TEN': 182, 'WAS': 221, 'DAL': 162, 'PHI': 229, 'NYG': 273, 'NE': 323, 'NYJ': 234, 'MIA': 205, 'BUF': 244, 'GB': 219, 'CHI': 214, 'MIN': 198, 'DET': 185, 'BAL': 226, 'PIT': 226, 'CLE': 186, 'CIN': 250, 'SF': 139, 'SEA': 228, 'ARI': 336, 'LAR': 179, 'LAC': 213, 'KC': 257, 'DEN': 222, 'OAK': 240}, {'CAR': 332, 'TB': 248, 'ATL': 221, 'NO': 261, 'IND': 249, 'HOU': 232, 'JAX': 236, 'TEN': 203, 'WAS': 241, 'DAL': 176, 'PHI': 243, 'NYG': 287, 'NE': 347, 'NYJ': 272, 'MIA': 225, 'BUF': 266, 'GB': 232, 'CHI': 231, 'MIN': 218, 'DET': 230, 'BAL': 259, 'PIT': 256, 'CLE': 213, 'CIN': 281, 'SF': 152, 'SEA': 267, 'ARI': 355, 'LAR': 186, 'LAC': 244, 'KC': 287, 'DEN': 252, 'OAK': 264}, {'CAR': 373, 'TB': 271, 'ATL': 240, 'NO': 299, 'IND': 259, 'HOU': 253, 'JAX': 275, 'TEN': 245, 'WAS': 257, 'DAL': 195, 'PHI': 278, 'NYG': 307, 'NE': 375, 'NYJ': 295, 'MIA': 240, 'BUF': 296, 'GB': 259, 'CHI': 251, 'MIN': 225, 'DET': 253, 'BAL': 272, 'PIT': 301, 'CLE': 216, 'CIN': 318, 'SF': 178, 'SEA': 305, 'ARI': 382, 'LAR': 189, 'LAC': 247, 'KC': 321, 'DEN': 269, 'OAK': 284}, {'CAR': 411, 'TB': 288, 'ATL': 240, 'NO': 323, 'IND': 275, 'HOU': 259, 'JAX': 326, 'TEN': 253, 'WAS': 281, 'DAL': 202, 'PHI': 301, 'NYG': 338, 'NE': 402, 'NYJ': 325, 'MIA': 264, 'BUF': 316, 'GB': 287, 'CHI': 272, 'MIN': 245, 'DET': 267, 'BAL': 278, 'PIT': 334, 'CLE': 240, 'CIN': 338, 'SF': 188, 'SEA': 340, 'ARI': 405, 'LAR': 210, 'LAC': 250, 'KC': 331, 'DEN': 281, 'OAK': 299}, {'CAR': 449, 'TB': 311, 'ATL': 263, 'NO': 350, 'IND': 285, 'HOU': 275, 'JAX': 343, 'TEN': 269, 'WAS': 316, 'DAL': 218, 'PHI': 318, 'NYG': 373, 'NE': 435, 'NYJ': 344, 'MIA': 278, 'BUF': 341, 'GB': 317, 'CHI': 289, 'MIN': 283, 'DET': 302, 'BAL': 292, 'PIT': 368, 'CLE': 253, 'CIN': 362, 'SF': 202, 'SEA': 370, 'ARI': 445, 'LAR': 241, 'LAC': 280, 'KC': 365, 'DEN': 308, 'OAK': 319}, {'CAR': 462, 'TB': 332, 'ATL': 283, 'NO': 388, 'IND': 303, 'HOU': 309, 'JAX': 370, 'TEN': 275, 'WAS': 354, 'DAL': 224, 'PHI': 342, 'NYG': 390, 'NE': 455, 'NYJ': 370, 'MIA': 290, 'BUF': 357, 'GB': 325, 'CHI': 315, 'MIN': 332, 'DET': 334, 'BAL': 312, 'PIT': 385, 'CLE': 266, 'CIN': 379, 'SF': 219, 'SEA': 387, 'ARI': 483, 'LAR': 264, 'LAC': 300, 'KC': 382, 'DEN': 328, 'OAK': 342}, {'CAR': 500, 'TB': 342, 'ATL': 300, 'NO': 408, 'IND': 333, 'HOU': 339, 'JAX': 376, 'TEN': 299, 'WAS': 388, 'DAL': 247, 'PHI': 377, 'NYG': 420, 'NE': 465, 'NYJ': 387, 'MIA': 310, 'BUF': 379, 'GB': 338, 'CHI': 335, 'MIN': 352, 'DET': 358, 'BAL': 328, 'PIT': 413, 'CLE': 278, 'CIN': 403, 'SF': 238, 'SEA': 423, 'ARI': 489, 'LAR': 280, 'LAC': 320, 'KC': 405, 'DEN': 355, 'OAK': 359}, {'CAR': 500, 'TB': 342, 'ATL': 300, 'NO': 408, 'IND': 333, 'HOU': 339, 'JAX': 376, 'TEN': 299, 'WAS': 406, 'DAL': 247, 'PHI': 377, 'NYG': 420, 'NE': 465, 'NYJ': 387, 'MIA': 310, 'BUF': 379, 'GB': 373, 'CHI': 335, 'MIN': 361, 'DET': 358, 'BAL': 328, 'PIT': 431, 'CLE': 278, 'CIN': 419, 'SF': 238, 'SEA': 433, 'ARI': 489, 'LAR': 280, 'LAC': 320, 'KC': 435, 'DEN': 355, 'OAK': 359}, {'CAR': 531, 'TB': 342, 'ATL': 300, 'NO': 408, 'IND': 333, 'HOU': 339, 'JAX': 376, 'TEN': 299, 'WAS': 406, 'DAL': 247, 'PHI': 377, 'NYG': 420, 'NE': 492, 'NYJ': 387, 'MIA': 310, 'BUF': 379, 'GB': 393, 'CHI': 335, 'MIN': 361, 'DET': 358, 'BAL': 328, 'PIT': 447, 'CLE': 278, 'CIN': 419, 'SF': 238, 'SEA': 457, 'ARI': 515, 'LAR': 280, 'LAC': 320, 'KC': 455, 'DEN': 378, 'OAK': 359}, {'CAR': 580, 'TB': 342, 'ATL': 300, 'NO': 408, 'IND': 333, 'HOU': 339, 'JAX': 376, 'TEN': 299, 'WAS': 406, 'DAL': 247, 'PHI': 377, 'NYG': 420, 'NE': 510, 'NYJ': 387, 'MIA': 310, 'BUF': 379, 'GB': 393, 'CHI': 335, 'MIN': 361, 'DET': 358, 'BAL': 328, 'PIT': 447, 'CLE': 278, 'CIN': 419, 'SF': 238, 'SEA': 457, 'ARI': 530, 'LAR': 280, 'LAC': 320, 'KC': 455, 'DEN': 398, 'OAK': 359}, {'CAR': 590, 'TB': 342, 'ATL': 300, 'NO': 408, 'IND': 333, 'HOU': 339, 'JAX': 376, 'TEN': 299, 'WAS': 406, 'DAL': 247, 'PHI': 377, 'NYG': 420, 'NE': 510, 'NYJ': 387, 'MIA': 310, 'BUF': 379, 'GB': 393, 'CHI': 335, 'MIN': 361, 'DET': 358, 'BAL': 328, 'PIT': 447, 'CLE': 278, 'CIN': 419, 'SF': 238, 'SEA': 457, 'ARI': 530, 'LAR': 280, 'LAC': 320, 'KC': 455, 'DEN': 422, 'OAK': 359}]

In [14]:
dict_week = 0 
current_week = 1


for game in season_2015_db.iterrows():
    if game[1][2] != current_week:
        current_week = game[1][2]
        dict_week = dict_week + 1
    favs_2015.append(week_score_2015[dict_week][game[1][10]])
    #favs_2015.append(week_score_2015[dict_week][game[1][12]])
    print(game[1][10])
    dogs_2015.append(week_score_2015[dict_week][game[1][11]])
    #print(game[1][11])

NE
ARI
IND
GB
DAL
DEN
KC
CAR
NYJ
OAK
LAC
SEA
TB
MIA
PHI
MIN
KC
BUF
CAR
ARI
CIN
TEN
GB
MIA
MIN
NO
NYG
BAL
PHI
PIT
LAR
IND
NYG
ARI
BAL
CAR
CLE
DEN
HOU
MIA
MIN
NE
NYJ
SEA
LAR
IND
GB
BAL
ARI
ATL
BUF
OAK
CIN
DEN
IND
NYJ
NO
LAC
GB
CAR
PHI
SEA
HOU
ATL
BAL
CIN
NE
ARI
GB
KC
NYG
DEN
PHI
TB
BUF
LAC
ATL
CIN
DEN
DET
GB
NE
JAX
MIN
NYJ
ARI
BAL
SEA
TEN
PHI
SEA
CAR
DET
IND
BUF
KC
MIA
NE
NYG
LAC
LAR
ATL
WAS
ARI
NE
ATL
BAL
MIN
ARI
SEA
GB
HOU
DET
NO
NYJ
LAR
CAR
CIN
BUF
GB
PHI
DEN
MIN
NE
NO
NYJ
PIT
ATL
NYG
LAC
NYJ
BAL
DEN
GB
NE
OAK
PHI
PIT
SEA
LAR
DAL
CAR
NO
CIN
JAX
ARI
ATL
BAL
CAR
DEN
OAK
NYJ
DAL
PHI
KC
SEA
NE
CAR
DET
GB
ATL
CIN
NE
HOU
IND
JAX
KC
NYJ
ARI
SEA
OAK
NYG
CLE
GB
BUF
CHI
CIN
MIA
SEA
NE
CAR
NYJ
KC
PIT
DEN
ARI
ATL
TEN
WAS
ARI
SEA
CAR
CHI
CIN
CLE
DEN
GB
NE
JAX
KC
NYJ
PHI
DET
TB
NYG
LAR
NYJ
KC
IND
JAX
MIN
NE
CAR
GB
ARI
PIT
LAC
CIN
SEA
BUF
NO
OAK
PHI
ARI
CAR
PIT
BUF
DET
KC
MIA
MIN
NO
NE
SEA
TB
HOU
DEN
ARI
ATL
NYJ
CAR
DET
CIN
PIT
DAL
DEN
GB
HOU
IND
KC
NE
NYG
LAR
PIT
KC
SEA
WAS
ARI
NE
CAR
DEN
CAR
NE
CAR

In [15]:
defense = {
    "CAR":0,
    "TB":0,
    'ATL':0,
    'NO':0,
    'IND':0,
    'HOU':0,
    'JAX':0,
    'TEN':0,
    'WAS':0,
    'DAL':0,
    'PHI':0,
    'NYG':0,
    'NE':0,
    'NYJ':0,
    'MIA':0,
    'BUF':0,
    'GB':0,
    'CHI':0,
    'MIN':0,
    'DET':0,
    'BAL':0,
    'PIT':0,
    'CLE':0,
    'CIN':0,
    'SF':0,
    'SEA':0,
    'ARI':0,
    'LAR':0,
    'LAC':0,
    'KC':0,
    'DEN':0,
    'OAK':0
}

In [16]:
week_defense_2015 = []
favs_d_2015 = []
dogs_d_2015 = []

In [17]:
current_week = 1
#current_year = 2015
for game in season_2015_db.iterrows():
    if game[1][2] != current_week:
        #print(game[1][4])
        week_defense_2015.append(defense.copy())
        current_week = game[1][2]
    defense[game[1][3]]+=game[1][5]
    defense[game[1][6]]+=game[1][4]
    if game[1][2] == 21:
        week_defense_2015.append(defense.copy())
        break

In [18]:
dict_week = 0 
current_week = 1


for game in season_2015_db.iterrows():
    if game[1][2] != current_week:
        current_week = game[1][2]
        dict_week = dict_week + 1
    favs_d_2015.append(week_defense_2015[dict_week][game[1][10]])
    #favs_2015.append(week_score_2015[dict_week][game[1][12]])
    #print(game[1][10])
    dogs_d_2015.append(week_defense_2015[dict_week][game[1][11]])
    #print(game[1][11])

In [19]:
season_2015_db['season_total_points_for _favorite'] = favs_2015

C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [20]:
season_2015_db['season_total_points_for _underdog'] = dogs_2015

C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [21]:
season_2015_db['season_total_points_against_favorite'] = favs_d_2015

C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [22]:
season_2015_db['season_total_points_against_underdog'] = dogs_d_2015

C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [65]:
season_2015_db.tail()

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,...,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog,favorite_win
259,1/17/2016,2015,19,CAR,31,24,SEA,-2.5,1,0,...,SEA,31,24,531,332,457,317,0,0,1
260,1/17/2016,2015,19,DEN,23,16,PIT,-7.5,1,0,...,PIT,23,16,378,312,447,342,0,0,1
261,1/24/2016,2015,20,CAR,49,15,ARI,-3.0,1,0,...,ARI,49,15,580,347,530,382,0,0,1
262,1/24/2016,2015,20,DEN,20,18,NE,-3.0,1,0,...,DEN,18,20,510,355,398,330,0,0,0
263,2/7/2016,2015,21,DEN,24,10,CAR,-4.5,1,0,...,DEN,10,24,590,371,422,340,0,0,0

In [23]:
#2016

In [24]:
scores = {
    "CAR":0,
    "TB":0,
    'ATL':0,
    'NO':0,
    'IND':0,
    'HOU':0,
    'JAX':0,
    'TEN':0,
    'WAS':0,
    'DAL':0,
    'PHI':0,
    'NYG':0,
    'NE':0,
    'NYJ':0,
    'MIA':0,
    'BUF':0,
    'GB':0,
    'CHI':0,
    'MIN':0,
    'DET':0,
    'BAL':0,
    'PIT':0,
    'CLE':0,
    'CIN':0,
    'SF':0,
    'SEA':0,
    'ARI':0,
    'LAR':0,
    'LAC':0,
    'KC':0,
    'DEN':0,
    'OAK':0
}

In [25]:
week_score_2016 = []
favs_2016 = []
dogs_2016 = []

In [26]:
current_week = 1
for game in season_2016_db.iterrows():
    #print(game[1])
    if game[1][2] != current_week:
        #print(game[1][4])
        week_score_2016.append(scores.copy())
        current_week = game[1][2]
    scores[game[1][3]]+=game[1][4]
    scores[game[1][6]]+=game[1][5]
    if game[1][2] == 21:
        week_score_2016.append(scores.copy())
        break

In [27]:
dict_week = 0 
current_week = 1


for game in season_2016_db.iterrows():
    if game[1][2] != current_week:
        current_week = game[1][2]
        dict_week = dict_week + 1
    favs_2016.append(week_score_2016[dict_week][game[1][10]])
    #favs_2015.append(week_score_2015[dict_week][game[1][12]])
    print(game[1][10])
    dogs_2016.append(week_score_2016[dict_week][game[1][11]])
    #print(game[1][11])

CAR
ARI
ATL
BAL
NYG
HOU
IND
GB
KC
NO
CIN
PHI
SEA
MIN
LAR
PIT
ARI
CAR
BAL
DEN
DET
HOU
SEA
GB
NE
NYG
OAK
PIT
LAC
WAS
CHI
NE
ARI
CAR
CIN
DAL
GB
IND
BAL
KC
MIA
NYG
PIT
SEA
TB
OAK
NO
CIN
ARI
CAR
BAL
DET
HOU
IND
NE
SEA
PIT
LAC
DAL
DEN
WAS
MIN
ARI
BAL
NE
CIN
DEN
PHI
GB
IND
BUF
MIA
MIN
OAK
PIT
CAR
DEN
BUF
CHI
DET
GB
HOU
PIT
NE
CAR
NYG
KC
SEA
TEN
PHI
ARI
GB
ARI
ATL
CIN
WAS
JAX
KC
NYG
BUF
NYJ
MIN
NE
SF
TEN
DEN
TEN
ATL
NE
CAR
CIN
NYJ
DAL
DEN
HOU
KC
SEA
TB
MIN
ATL
PIT
DAL
GB
KC
CAR
MIA
MIN
NYG
OAK
LAC
NO
SEA
BAL
ARI
CAR
JAX
NE
NO
LAR
PHI
PIT
LAC
CHI
GB
WAS
CAR
CIN
PIT
DAL
DET
IND
KC
MIA
MIN
NYG
NE
SEA
WAS
OAK
DAL
DET
PIT
ATL
BAL
BUF
TEN
NYG
DEN
LAC
MIA
NO
NE
OAK
SEA
PHI
DAL
ARI
ATL
BAL
SF
CIN
GB
DEN
NE
NO
OAK
PIT
LAC
SEA
NYJ
KC
PIT
CAR
CIN
DET
SEA
IND
MIN
ATL
ARI
DAL
WAS
SF
TB
TEN
NE
SEA
MIA
ARI
ATL
BAL
BUF
GB
PIT
DAL
NE
HOU
KC
MIN
NYG
OAK
WAS
PHI
BUF
ATL
WAS
LAC
GB
HOU
TEN
LAR
NE
NO
OAK
SEA
KC
PIT
DAL
ATL
BAL
DEN
GB
IND
ARI
NE
MIN
BUF
PHI
PIT
KC
SEA
TB
TEN
WAS
HOU
SEA
GB
PIT
ATL
NE
DAL
KC
ATL
NE
NE

In [28]:
defense = {
    "CAR":0,
    "TB":0,
    'ATL':0,
    'NO':0,
    'IND':0,
    'HOU':0,
    'JAX':0,
    'TEN':0,
    'WAS':0,
    'DAL':0,
    'PHI':0,
    'NYG':0,
    'NE':0,
    'NYJ':0,
    'MIA':0,
    'BUF':0,
    'GB':0,
    'CHI':0,
    'MIN':0,
    'DET':0,
    'BAL':0,
    'PIT':0,
    'CLE':0,
    'CIN':0,
    'SF':0,
    'SEA':0,
    'ARI':0,
    'LAR':0,
    'LAC':0,
    'KC':0,
    'DEN':0,
    'OAK':0
}

In [29]:
week_defense_2016 = []
favs_d_2016 = []
dogs_d_2016 = []

In [30]:
current_week = 1
#current_year = 2015
for game in season_2016_db.iterrows():
    if game[1][2] != current_week:
        #print(game[1][4])
        week_defense_2016.append(defense.copy())
        current_week = game[1][2]
    defense[game[1][3]]+=game[1][5]
    defense[game[1][6]]+=game[1][4]
    if game[1][2] == 21:
        week_defense_2016.append(defense.copy())
        break

In [31]:
dict_week = 0 
current_week = 1


for game in season_2016_db.iterrows():
    if game[1][2] != current_week:
        current_week = game[1][2]
        dict_week = dict_week + 1
    favs_d_2016.append(week_defense_2016[dict_week][game[1][10]])
    #favs_2015.append(week_score_2015[dict_week][game[1][12]])
    #print(game[1][10])
    dogs_d_2016.append(week_defense_2016[dict_week][game[1][11]])
    #print(game[1][11])

In [32]:
season_2016_db['season_total_points_against_favorite'] = favs_d_2016

C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
season_2016_db['season_total_points_against_underdog'] = dogs_d_2016

C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
season_2016_db['season_total_points_for _favorite'] = favs_2016
season_2016_db['season_total_points_for _underdog'] = dogs_2016

C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [35]:
season_2016_db.tail()

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,...,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog,favorite_win
524,1/15/2017,2016,19,DAL,31,34,GB,-5.5,0,1,...,GB,31,34,452,340,504,432,0,0,0
525,1/15/2017,2016,19,KC,16,18,PIT,-2.5,0,1,...,PIT,16,18,405,329,447,355,0,0,0
526,1/22/2017,2016,20,ATL,44,21,GB,-6.5,1,0,...,GB,44,21,620,447,525,476,0,0,1
527,1/22/2017,2016,20,NE,36,17,PIT,-5.5,1,0,...,PIT,36,17,511,283,464,391,0,0,1
528,2/5/2017,2016,21,NE,34,28,ATL,-3.0,1,0,...,ATL,34,28,545,311,648,481,0,0,1

In [36]:
#2017

In [37]:
scores = {
    "CAR":0,
    "TB":0,
    'ATL':0,
    'NO':0,
    'IND':0,
    'HOU':0,
    'JAX':0,
    'TEN':0,
    'WAS':0,
    'DAL':0,
    'PHI':0,
    'NYG':0,
    'NE':0,
    'NYJ':0,
    'MIA':0,
    'BUF':0,
    'GB':0,
    'CHI':0,
    'MIN':0,
    'DET':0,
    'BAL':0,
    'PIT':0,
    'CLE':0,
    'CIN':0,
    'SF':0,
    'SEA':0,
    'ARI':0,
    'LAR':0,
    'LAC':0,
    'KC':0,
    'DEN':0,
    'OAK':0
}

In [38]:
week_score_2017 = []
favs_2017 = []
dogs_2017 = []

In [39]:
current_week = 1
for game in season_2017_db.iterrows():
    #print(game[1])
    if game[1][2] != current_week:
        #print(game[1][4])
        week_score_2017.append(scores.copy())
        current_week = game[1][2]
    scores[game[1][3]]+=game[1][4]
    scores[game[1][6]]+=game[1][5]
    if game[1][2] == 21:
        week_score_2017.append(scores.copy())
        break

In [40]:
dict_week = 0 
current_week = 1


for game in season_2017_db.iterrows():
    if game[1][2] != current_week:
        current_week = game[1][2]
        dict_week = dict_week + 1
    favs_2017.append(week_score_2017[dict_week][game[1][10]])
    #favs_2015.append(week_score_2015[dict_week][game[1][12]])
    print(game[1][10])
    dogs_2017.append(week_score_2017[dict_week][game[1][11]])
    #print(game[1][11])

NE
BUF
ATL
CIN
PIT
DAL
ARI
GB
HOU
IND
CAR
TEN
PHI
DEN
MIN
CIN
ATL
BAL
CAR
DAL
ARI
TEN
KC
LAC
LAR
NE
OAK
PIT
SEA
TB
NYG
LAR
DEN
CAR
PIT
ATL
GB
CLE
BAL
KC
TB
NE
MIA
PHI
TEN
OAK
DAL
GB
ARI
ATL
PIT
CIN
DAL
DEN
TEN
LAC
NO
MIN
NE
JAX
SEA
TB
KC
NE
CIN
NYJ
DAL
DET
KC
IND
LAR
TEN
NYG
OAK
PHI
PIT
MIN
CAR
TB
ATL
BAL
DEN
HOU
JAX
KC
GB
NO
NE
OAK
WAS
TEN
KC
BUF
CAR
TEN
NO
JAX
DEN
LAR
MIA
MIN
NE
SEA
PIT
DAL
PHI
BAL
BUF
CIN
MIN
PIT
NE
NO
ATL
PHI
SEA
TB
DAL
KC
BUF
ATL
DAL
HOU
JAX
OAK
NO
LAR
PHI
ARI
SEA
TEN
DET
SEA
ATL
NO
CHI
NE
DET
PIT
JAX
LAR
NYG
TB
TEN
MIN
CAR
PIT
DET
JAX
PHI
DEN
BAL
HOU
LAC
TB
MIN
NO
KC
NE
SEA
LAC
MIN
WAS
JAX
ATL
CIN
TEN
KC
LAR
NE
CAR
OAK
PHI
PIT
SEA
BAL
WAS
LAR
ATL
BAL
NE
CHI
GB
JAX
LAC
DEN
NO
KC
OAK
PHI
TEN
PIT
ATL
TEN
BUF
MIN
CIN
GB
NYJ
HOU
JAX
KC
LAC
LAR
DAL
PIT
NE
DEN
DET
LAC
BUF
CAR
BAL
JAX
MIN
NO
PHI
DAL
NE
SF
LAR
WAS
ATL
BAL
MIN
ARI
CAR
CHI
DET
DAL
KC
NE
NO
LAC
JAX
LAR
WAS
PIT
PHI
ATL
BAL
DEN
DET
IND
LAC
SF
BUF
MIN
NE
WAS
DAL
PIT
SEA
NO
TEN
KC
LAR
JAX
NO
NE
ATL
MIN
PIT
NE
MIN
NE

In [41]:
season_2017_db['season_total_points_for _favorite'] = favs_2017
season_2017_db['season_total_points_for _underdog'] = dogs_2017

C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [42]:
defense = {
    "CAR":0,
    "TB":0,
    'ATL':0,
    'NO':0,
    'IND':0,
    'HOU':0,
    'JAX':0,
    'TEN':0,
    'WAS':0,
    'DAL':0,
    'PHI':0,
    'NYG':0,
    'NE':0,
    'NYJ':0,
    'MIA':0,
    'BUF':0,
    'GB':0,
    'CHI':0,
    'MIN':0,
    'DET':0,
    'BAL':0,
    'PIT':0,
    'CLE':0,
    'CIN':0,
    'SF':0,
    'SEA':0,
    'ARI':0,
    'LAR':0,
    'LAC':0,
    'KC':0,
    'DEN':0,
    'OAK':0
}

In [43]:
week_defense_2017 = []
favs_d_2017 = []
dogs_d_2017 = []

In [44]:
current_week = 1
#current_year = 2015
for game in season_2017_db.iterrows():
    if game[1][2] != current_week:
        #print(game[1][4])
        week_defense_2017.append(defense.copy())
        current_week = game[1][2]
    defense[game[1][3]]+=game[1][5]
    defense[game[1][6]]+=game[1][4]
    if game[1][2] == 21:
        week_defense_2017.append(defense.copy())
        break

In [45]:
dict_week = 0 
current_week = 1


for game in season_2017_db.iterrows():
    if game[1][2] != current_week:
        current_week = game[1][2]
        dict_week = dict_week + 1
    favs_d_2017.append(week_defense_2017[dict_week][game[1][10]])
    #favs_2015.append(week_score_2015[dict_week][game[1][12]])
    #print(game[1][10])
    dogs_d_2017.append(week_defense_2017[dict_week][game[1][11]])
    #print(game[1][11])

In [46]:
season_2017_db['season_total_points_against_favorite'] = favs_d_2017
season_2017_db['season_total_points_against_underdog'] = dogs_d_2017

C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [47]:
season_2017_db.tail()

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,...,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog,favorite_win
790,1/14/2018,2017,19,MIN,29,24,NO,-5.5,1,0,...,NO,29,24,411,276,503,381,0,0,1
791,1/14/2018,2017,19,PIT,42,45,JAX,-7.0,0,1,...,JAX,42,45,448,353,472,313,0,0,0
792,1/21/2018,2017,20,NE,24,20,JAX,-7.5,1,0,...,JAX,24,20,517,330,492,337,0,0,1
793,1/21/2018,2017,20,PHI,38,7,MIN,-3.0,1,0,...,PHI,7,38,418,314,510,312,0,0,0
794,2/4/2018,2017,21,NE,33,41,PHI,-4.5,0,1,...,PHI,33,41,550,371,551,345,0,0,0

In [48]:
#2018

In [49]:
scores = {
    "CAR":0,
    "TB":0,
    'ATL':0,
    'NO':0,
    'IND':0,
    'HOU':0,
    'JAX':0,
    'TEN':0,
    'WAS':0,
    'DAL':0,
    'PHI':0,
    'NYG':0,
    'NE':0,
    'NYJ':0,
    'MIA':0,
    'BUF':0,
    'GB':0,
    'CHI':0,
    'MIN':0,
    'DET':0,
    'BAL':0,
    'PIT':0,
    'CLE':0,
    'CIN':0,
    'SF':0,
    'SEA':0,
    'ARI':0,
    'LAR':0,
    'LAC':0,
    'KC':0,
    'DEN':0,
    'OAK':0
}

In [50]:
week_score_2018 = []
favs_2018 = []
dogs_2018 = []

In [51]:
current_week = 1
for game in season_2018_db.iterrows():
    #print(game[1])
    if game[1][2] != current_week:
        #print(game[1][4])
        week_score_2018.append(scores.copy())
        current_week = game[1][2]
    scores[game[1][3]]+=game[1][4]
    scores[game[1][6]]+=game[1][5]
    if game[1][2] == 21:
        week_score_2018.append(scores.copy())
        break

In [52]:
dict_week = 0 
current_week = 1


for game in season_2018_db.iterrows():
    if game[1][2] != current_week:
        current_week = game[1][2]
        dict_week = dict_week + 1
    favs_2018.append(week_score_2018[dict_week][game[1][10]])
    #favs_2015.append(week_score_2015[dict_week][game[1][12]])
    print(game[1][10])
    dogs_2018.append(week_score_2018[dict_week][game[1][11]])
    #print(game[1][11])

PHI
ARI
BAL
CAR
PIT
DEN
GB
CIN
LAC
TEN
MIN
NE
NO
JAX
DET
LAR
CIN
ATL
LAC
DAL
DEN
MIN
NE
LAR
NO
NYJ
PIT
SF
PHI
HOU
WAS
CHI
CLE
CHI
ATL
BAL
CAR
NE
HOU
JAX
KC
LAR
MIA
MIN
PHI
SEA
GB
PIT
LAR
SEA
ATL
CHI
DAL
GB
IND
JAX
LAC
NE
NO
OAK
PIT
PHI
KC
NE
TEN
CAR
CIN
BAL
GB
HOU
KC
LAC
NYJ
PHI
PIT
SF
LAR
NO
PHI
ATL
CIN
CLE
JAX
LAR
HOU
CHI
MIN
NE
NYJ
SEA
BAL
CAR
GB
DEN
BAL
NE
IND
JAX
KC
LAC
DET
MIN
PHI
LAR
TB
DAL
ATL
HOU
ARI
BAL
CHI
CIN
DET
PHI
KC
LAR
MIN
WAS
IND
PIT
NE
OAK
BAL
CHI
CAR
KC
DEN
MIA
MIN
NE
LAR
SEA
WAS
DAL
PIT
CHI
NO
ATL
GB
IND
KC
LAR
NYJ
LAC
PHI
TB
NE
SF
SEA
ARI
ATL
BAL
CHI
CAR
IND
PIT
LAC
NO
NYG
HOU
LAR
DAL
CHI
NO
BAL
JAX
CAR
CLE
PIT
IND
LAC
MIN
NE
PHI
TB
HOU
NO
ATL
DEN
LAR
GB
HOU
IND
MIA
NE
CHI
KC
PIT
SEA
CAR
TEN
PHI
TEN
DET
BUF
LAR
CAR
DAL
GB
HOU
KC
LAC
NE
PIT
DEN
NO
NYG
SEA
KC
DEN
HOU
ATL
BAL
BUF
CHI
CIN
IND
JAX
LAR
MIN
TEN
NE
SEA
NO
LAC
TEN
LAR
ATL
CLE
DAL
MIN
IND
MIA
NE
NO
GB
PHI
CHI
KC
DEN
BAL
BUF
LAC
GB
HOU
KC
LAR
MIN
NE
NO
NYG
PIT
SEA
ATL
IND
PHI
DAL
HOU
BAL
CHI
KC
LAR
NE
NO
KC
NO
NE

In [53]:
season_2018_db['season_total_points_for _favorite'] = favs_2018
season_2018_db['season_total_points_for _underdog'] = dogs_2018

C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [54]:
defense = {
    "CAR":0,
    "TB":0,
    'ATL':0,
    'NO':0,
    'IND':0,
    'HOU':0,
    'JAX':0,
    'TEN':0,
    'WAS':0,
    'DAL':0,
    'PHI':0,
    'NYG':0,
    'NE':0,
    'NYJ':0,
    'MIA':0,
    'BUF':0,
    'GB':0,
    'CHI':0,
    'MIN':0,
    'DET':0,
    'BAL':0,
    'PIT':0,
    'CLE':0,
    'CIN':0,
    'SF':0,
    'SEA':0,
    'ARI':0,
    'LAR':0,
    'LAC':0,
    'KC':0,
    'DEN':0,
    'OAK':0
}

In [55]:
week_defense_2018 = []
favs_d_2018 = []
dogs_d_2018 = []

In [56]:
current_week = 1
#current_year = 2015
for game in season_2018_db.iterrows():
    if game[1][2] != current_week:
        #print(game[1][4])
        week_defense_2018.append(defense.copy())
        current_week = game[1][2]
    defense[game[1][3]]+=game[1][5]
    defense[game[1][6]]+=game[1][4]
    if game[1][2] == 21:
        week_defense_2018.append(defense.copy())
        break

In [57]:
dict_week = 0 
current_week = 1


for game in season_2018_db.iterrows():
    if game[1][2] != current_week:
        current_week = game[1][2]
        dict_week = dict_week + 1
    favs_d_2018.append(week_defense_2018[dict_week][game[1][10]])
    #favs_2015.append(week_score_2015[dict_week][game[1][12]])
    #print(game[1][10])
    dogs_d_2018.append(week_defense_2018[dict_week][game[1][11]])
    #print(game[1][11])

In [58]:
season_2018_db['season_total_points_against_favorite'] = favs_d_2018
season_2018_db['season_total_points_against_underdog'] = dogs_d_2018

C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\kylem\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [59]:
season_2018_db.tail()

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,...,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog,favorite_win
1057,1/13/2019,2018,19,NE,41,28,LAC,-3.5,1,0,...,LAC,41,28,477,353,479,387,0,0,1
1058,1/13/2019,2018,19,NO,20,14,PHI,-8.5,1,0,...,PHI,20,14,524,367,397,383,0,0,1
1059,1/20/2019,2018,20,KC,31,37,NE,-3.0,0,1,...,NE,31,37,627,471,514,384,0,0,0
1060,1/20/2019,2018,20,NO,23,26,LAR,-3.0,0,1,...,LAR,23,26,547,393,583,429,0,0,0
1061,2/3/2019,2018,21,LAR,3,13,NE,-2.0,0,1,...,LAR,13,3,527,387,586,442,0,0,1

In [60]:
seasons = [season_2015_db, season_2016_db, season_2017_db, season_2018_db]

In [61]:
final_db = pd.concat(seasons, sort = False)

In [64]:
final_db.tail()

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,...,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog,favorite_win
1057,1/13/2019,2018,19,NE,41,28,LAC,-3.5,1,0,...,LAC,41,28,477,353,479,387,0,0,1
1058,1/13/2019,2018,19,NO,20,14,PHI,-8.5,1,0,...,PHI,20,14,524,367,397,383,0,0,1
1059,1/20/2019,2018,20,KC,31,37,NE,-3.0,0,1,...,NE,31,37,627,471,514,384,0,0,0
1060,1/20/2019,2018,20,NO,23,26,LAR,-3.0,0,1,...,LAR,23,26,547,393,583,429,0,0,0
1061,2/3/2019,2018,21,LAR,3,13,NE,-2.0,0,1,...,LAR,13,3,527,387,586,442,0,0,1

In [63]:
final_db.to_csv("../data/train_test_data.csv", index = False)