In [12]:
import pandas as pd
import numpy as np

In [13]:
results_db = pd.read_csv("../data/game_data.csv")
results_db.tail(10)

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,favorite,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog
1058,1/5/2019,2018,Wildcard,HOU,7,21,IND,-2.0,0,1,HOU,IND,0.0,0,0,0,0,0,0,0
1059,1/6/2019,2018,Wildcard,BAL,17,23,LAC,-3.0,0,1,BAL,LAC,0.0,0,0,0,0,0,0,0
1060,1/6/2019,2018,Wildcard,CHI,15,16,PHI,-6.5,0,1,CHI,PHI,0.0,0,0,0,0,0,0,0
1061,1/12/2019,2018,Division,KC,31,13,IND,-4.0,1,0,KC,IND,0.0,0,0,0,0,0,0,0
1062,1/12/2019,2018,Division,LAR,30,22,DAL,-7.5,1,0,LAR,DAL,0.0,0,0,0,0,0,0,0
1063,1/13/2019,2018,Division,NE,41,28,LAC,-3.5,1,0,NE,LAC,0.0,0,0,0,0,0,0,0
1064,1/13/2019,2018,Division,NO,20,14,PHI,-8.5,1,0,NO,PHI,0.0,0,0,0,0,0,0,0
1065,1/20/2019,2018,Conference,KC,31,37,NE,-3.0,0,1,KC,NE,0.0,0,0,0,0,0,0,0
1066,1/20/2019,2018,Conference,NO,23,26,LAR,-3.0,0,1,NO,LAR,0.0,0,0,0,0,0,0,0
1067,2/3/2019,2018,Superbowl,LAR,3,13,NE,-2.0,0,1,NE,LAR,0.0,0,0,0,0,0,0,0

In [14]:
def underdog_score(game):
    if game['underdog'] == game['team_home']:
        return game['score_home']
    else:
        return game['score_away']

results_db['score_underdog'] = results_db.apply(underdog_score, axis=1)

In [15]:
def favorite_score(game):
    if game['favorite'] == game['team_home']:
        return game['score_home']
    else:
        return game['score_away']

results_db['score_favorite'] = results_db.apply(favorite_score, axis=1)

In [16]:
results_db.head(16)

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,favorite,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog
0,9/10/2015,2015,1,NE,28,21,PIT,-7.0,1,0,NE,PIT,28,21,28,21,21,28,1,0
1,9/13/2015,2015,1,ARI,31,19,NO,-2.5,1,0,ARI,NO,31,19,31,19,19,31,1,0
2,9/13/2015,2015,1,BUF,27,14,IND,-1.0,1,0,IND,BUF,14,27,14,27,27,14,0,1
3,9/13/2015,2015,1,CHI,23,31,GB,-6.5,0,1,GB,CHI,31,23,31,23,23,31,1,0
4,9/13/2015,2015,1,DAL,27,26,NYG,-7.0,1,0,DAL,NYG,27,26,27,26,26,27,1,0
5,9/13/2015,2015,1,DEN,19,13,BAL,-4.5,1,0,DEN,BAL,19,13,19,13,13,19,1,0
6,9/13/2015,2015,1,HOU,20,27,KC,-1.0,0,1,KC,HOU,27,20,0,0,0,0,0,0
7,9/13/2015,2015,1,JAX,9,20,CAR,-3.0,0,1,CAR,JAX,20,9,0,0,0,0,0,0
8,9/13/2015,2015,1,NYJ,31,10,CLE,-3.5,1,0,NYJ,CLE,31,10,0,0,0,0,0,0
9,9/13/2015,2015,1,OAK,13,33,CIN,-3.0,0,1,OAK,CIN,13,33,0,0,0,0,0,0
10,9/13/2015,2015,1,LAC,33,28,DET,-3.5,1,0,LAC,DET,33,28,0,0,0,0,0,0
11,9/13/2015,2015,1,LAR,34,31,SEA,-3.5,1,0,SEA,LAR,31,34,0,0,0,0,0,0
12,9/13/2015,2015,1,TB,14,42,TEN,-3.0,0,1,TB,TEN,14,42,0,0,0,0,0,0
13,9/13/2015,2015,1,WAS,10,17,MIA,-4.0,0,1,MIA,WAS,17,10,0,0,0,0,0,0
14,9/14/2015,2015,1,ATL,26,24,PHI,-3.0,1,0,PHI,ATL,24,26,0,0,0,0,0,0
15,9/14/2015,2015,1,SF,20,3,MIN,-2.5,1,0,MIN,SF,3,20,0,0,0,0,0,0

In [54]:
scores = {
    "CAR":0,
    "TB":0,
    'ATL':0,
    'NO':0,
    'IND':0,
    'HOU':0,
    'JAX':0,
    'TEN':0,
    'WAS':0,
    'DAL':0,
    'PHI':0,
    'NYG':0,
    'NE':0,
    'NYJ':0,
    'MIA':0,
    'BUF':0,
    'GB':0,
    'CHI':0,
    'MIN':0,
    'DET':0,
    'BAL':0,
    'PIT':0,
    'CLE':0,
    'CIN':0,
    'SF':0,
    'SEA':0,
    'ARI':0,
    'LAR':0,
    'LAC':0,
    'KC':0,
    'DEN':0,
    'OAK':0
}

In [51]:
current_week = '1'
current_year = 2015
for game in results_db.iterrows():
    #print(game[1])
    if game[1][2] == current_week and game[1][1] == current_year:
        print(game[1][4])
        scores[game[1][3]]+=game[1][4]
        scores[game[1][6]]+=game[1][5]

24
32
24
23
24
28
27
23
26
19
20
37
10
43
24
7

In [59]:
print(scores)

{'CAR': 71, 'TB': 49, 'ATL': 89, 'NO': 60, 'IND': 56, 'HOU': 56, 'JAX': 49, 'TEN': 89, 'WAS': 55, 'DAL': 75, 'PHI': 58, 'NYG': 78, 'NE': 119, 'NYJ': 68, 'MIA': 51, 'BUF': 100, 'GB': 96, 'CHI': 46, 'MIN': 60, 'DET': 56, 'BAL': 70, 'PIT': 76, 'CLE': 58, 'CIN': 85, 'SF': 45, 'SEA': 74, 'ARI': 126, 'LAR': 50, 'LAC': 66, 'KC': 79, 'DEN': 74, 'OAK': 77}

In [24]:
current_week = 2
current_year = 2015
score_items = scores.items()
for team in list(scores):
    #print(team)
    score = int(scores[team])
    #print(score)
    games = results_db.iterrows();
    for game in games:
        week = game[1];
        #print(week['schedule_week'])
        #print(week['schedule_week'])
        #print(week['schedule_week'])
        try:
          i = int(week['schedule_week'])
        except Exception as ex:
            continue
        if current_week != int(week['schedule_week']):
                continue;
        #print(team)
        #print(score)
        if int(week['schedule_week']) == current_week and int(week['schedule_season']) == current_year:
            if team == week['favorite']:
                score = score + int(week['score_favorite'])
                week['season_total_points_for _favorite']=score
                #print(week)
            elif team == week['underdog']:
                score = score + int(week['score_underdog'])
                week['season_total_points_for _underdog'] = score
                #print(week)

In [28]:
#score_items = scores.items()
#print(list(scores))

In [23]:
#results_db.head(200)

In [58]:
current_week = '3'
current_year = 2015
for game in results_db.iterrows():
    #print(game[1])
    if game[1][2] == current_week and game[1][1] == current_year:
        print(game[1][4])
        scores[game[1][3]]+=game[1][4]
        scores[game[1][6]]+=game[1][5]



score_items = scores.items()
for team in score_items:
    for game in results_db.iterrows():
        if game[1][2] == current_week and game[1][1] == current_year:
            if team[0] == game[1][10]:
                print(team)
                game[1][14] = team[1]
            elif team[0] == game[1][11]:
                print(team)
                game[1][16] = team[1]

32
47
24
27
20
28
12
19
14
31
51
17
26
6
33
38
('CAR', 71)
('TB', 49)
('NO', 60)
('IND', 56)
('HOU', 56)
('JAX', 49)
('TEN', 89)
('WAS', 55)
('PHI', 58)
('NYG', 78)
('NE', 119)
('NYJ', 68)
('MIA', 51)
('BUF', 100)
('GB', 96)
('CHI', 46)
('MIN', 60)
('DET', 56)
('BAL', 70)
('PIT', 76)
('CLE', 58)
('CIN', 85)
('SF', 45)
('SEA', 74)
('ARI', 126)
('LAR', 50)
('LAC', 66)
('KC', 79)
('DEN', 74)
('OAK', 77)

In [53]:
results_db.head(32)

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,favorite,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog
0,9/10/2015,2015,1,NE,28,21,PIT,-7.0,1,0,NE,PIT,28,21,28,21,21,28,1,0
1,9/13/2015,2015,1,ARI,31,19,NO,-2.5,1,0,ARI,NO,31,19,31,19,19,31,1,0
2,9/13/2015,2015,1,BUF,27,14,IND,-1.0,1,0,IND,BUF,14,27,14,27,27,14,0,1
3,9/13/2015,2015,1,CHI,23,31,GB,-6.5,0,1,GB,CHI,31,23,31,23,23,31,1,0
4,9/13/2015,2015,1,DAL,27,26,NYG,-7.0,1,0,DAL,NYG,27,26,27,26,26,27,1,0
5,9/13/2015,2015,1,DEN,19,13,BAL,-4.5,1,0,DEN,BAL,19,13,19,13,13,19,1,0
6,9/13/2015,2015,1,HOU,20,27,KC,-1.0,0,1,KC,HOU,27,20,0,0,0,0,0,0
7,9/13/2015,2015,1,JAX,9,20,CAR,-3.0,0,1,CAR,JAX,20,9,0,0,0,0,0,0
8,9/13/2015,2015,1,NYJ,31,10,CLE,-3.5,1,0,NYJ,CLE,31,10,0,0,0,0,0,0
9,9/13/2015,2015,1,OAK,13,33,CIN,-3.0,0,1,OAK,CIN,13,33,0,0,0,0,0,0
10,9/13/2015,2015,1,LAC,33,28,DET,-3.5,1,0,LAC,DET,33,28,0,0,0,0,0,0
11,9/13/2015,2015,1,LAR,34,31,SEA,-3.5,1,0,SEA,LAR,31,34,0,0,0,0,0,0
12,9/13/2015,2015,1,TB,14,42,TEN,-3.0,0,1,TB,TEN,14,42,0,0,0,0,0,0
13,9/13/2015,2015,1,WAS,10,17,MIA,-4.0,0,1,MIA,WAS,17,10,0,0,0,0,0,0
14,9/14/2015,2015,1,ATL,26,24,PHI,-3.0,1,0,PHI,ATL,24,26,0,0,0,0,0,0
15,9/14/2015,2015,1,SF,20,3,MIN,-2.5,1,0,MIN,SF,3,20,0,0,0,0,0,0
16,9/17/2015,2015,2,KC,24,31,DEN,-3.0,0,1,KC,DEN,24,31,0,0,0,0,0,0
17,9/20/2015,2015,2,BUF,32,40,NE,-1.0,0,1,BUF,NE,32,40,0,0,0,0,0,0
18,9/20/2015,2015,2,CAR,24,17,HOU,-3.0,1,0,CAR,HOU,24,17,0,0,0,0,0,0
19,9/20/2015,2015,2,CHI,23,48,ARI,-2.0,0,1,ARI,CHI,48,23,0,0,0,0,0,0
20,9/20/2015,2015,2,CIN,24,19,LAC,-3.5,1,0,CIN,LAC,24,19,0,0,0,0,0,0
21,9/20/2015,2015,2,CLE,28,14,TEN,-1.0,1,0,TEN,CLE,14,28,0,0,0,0,0,0
22,9/20/2015,2015,2,GB,27,17,SEA,-3.0,1,0,GB,SEA,27,17,0,0,0,0,0,0
23,9/20/2015,2015,2,JAX,23,20,MIA,-6.0,1,0,MIA,JAX,20,23,0,0,0,0,0,0
24,9/20/2015,2015,2,MIN,26,16,DET,-2.5,1,0,MIN,DET,26,16,0,0,0,0,0,0
25,9/20/2015,2015,2,NO,19,26,TB,-9.0,0,1,NO,TB,19,26,0,0,0,0,0,0
26,9/20/2015,2015,2,NYG,20,24,ATL,-2.0,0,1,NYG,ATL,20,24,0,0,0,0,0,0
27,9/20/2015,2015,2,OAK,37,33,BAL,-6.0,1,0,BAL,OAK,33,37,0,0,0,0,0,0
28,9/20/2015,2015,2,PHI,10,20,DAL,-6.5,0,1,PHI,DAL,10,20,0,0,0,0,0,0
29,9/20/2015,2015,2,PIT,43,18,SF,-6.0,1,0,PIT,SF,43,18,0,0,0,0,0,0
30,9/20/2015,2015,2,WAS,24,10,LAR,-3.0,1,0,LAR,WAS,10,24,0,0,0,0,0,0
31,9/21/2015,2015,2,IND,7,20,NYJ,-6.0,0,1,IND,NYJ,7,20,0,0,0,0,0,0