In [1]:
import pandas as pd
import numpy as np

In [2]:
results_db = pd.read_csv("../data/game_data.csv")
results_db.tail(10)

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,favorite,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog
1052,1/5/2019,2018,18,HOU,7,21,IND,-2.0,0,1,HOU,IND,0,0,0,0,0,0,0,0
1053,1/6/2019,2018,18,BAL,17,23,LAC,-3.0,0,1,BAL,LAC,0,0,0,0,0,0,0,0
1054,1/6/2019,2018,18,CHI,15,16,PHI,-6.5,0,1,CHI,PHI,0,0,0,0,0,0,0,0
1055,1/12/2019,2018,19,KC,31,13,IND,-4.0,1,0,KC,IND,0,0,0,0,0,0,0,0
1056,1/12/2019,2018,19,LAR,30,22,DAL,-7.5,1,0,LAR,DAL,0,0,0,0,0,0,0,0
1057,1/13/2019,2018,19,NE,41,28,LAC,-3.5,1,0,NE,LAC,0,0,501,0,0,0,0,0
1058,1/13/2019,2018,19,NO,20,14,PHI,-8.5,1,0,NO,PHI,0,476,0,0,0,0,0,0
1059,1/20/2019,2018,20,KC,31,37,NE,-3.0,0,1,KC,NE,0,0,0,0,538,0,0,0
1060,1/20/2019,2018,20,NO,23,26,LAR,-3.0,0,1,NO,LAR,0,499,0,0,0,0,0,0
1061,2/3/2019,2018,21,LAR,3,13,NE,-2.0,0,1,NE,LAR,0,0,551,0,0,0,0,0

In [3]:
def underdog_score(game):
    if game['underdog'] == game['team_home']:
        return game['score_home']
    else:
        return game['score_away']

results_db['score_underdog'] = results_db.apply(underdog_score, axis=1)

In [4]:
def favorite_score(game):
    if game['favorite'] == game['team_home']:
        return game['score_home']
    else:
        return game['score_away']

results_db['score_favorite'] = results_db.apply(favorite_score, axis=1)

In [68]:
season_2015 = results_db['schedule_season'] == 2015
season_2016 = results_db['schedule_season'] == 2016
season_2017 = results_db['schedule_season'] == 2017
season_2018 = results_db['schedule_season'] == 2018

In [69]:
season_2015_db = results_db[season_2015]
season_2016_db = results_db[season_2016]
season_2017_db = results_db[season_2017]
season_2018_db = results_db[season_2018]

In [199]:
season_2015_db.tail()

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,...,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog,season_total_points_for_favorite,season_total_points_for_underdog
259,1/17/2016,2015,19,CAR,31,24,SEA,-2.5,1,0,...,31,24,531,0,457,0,0,0,531,457
260,1/17/2016,2015,19,DEN,23,16,PIT,-7.5,1,0,...,23,16,378,0,447,0,0,0,378,447
261,1/24/2016,2015,20,CAR,49,15,ARI,-3.0,1,0,...,49,15,580,0,530,0,0,0,580,530
262,1/24/2016,2015,20,DEN,20,18,NE,-3.0,1,0,...,18,20,510,0,398,0,0,0,510,398
263,2/7/2016,2015,21,DEN,24,10,CAR,-4.5,1,0,...,10,24,590,0,422,0,0,0,590,422

In [182]:
scores = {
    "CAR":0,
    "TB":0,
    'ATL':0,
    'NO':0,
    'IND':0,
    'HOU':0,
    'JAX':0,
    'TEN':0,
    'WAS':0,
    'DAL':0,
    'PHI':0,
    'NYG':0,
    'NE':0,
    'NYJ':0,
    'MIA':0,
    'BUF':0,
    'GB':0,
    'CHI':0,
    'MIN':0,
    'DET':0,
    'BAL':0,
    'PIT':0,
    'CLE':0,
    'CIN':0,
    'SF':0,
    'SEA':0,
    'ARI':0,
    'LAR':0,
    'LAC':0,
    'KC':0,
    'DEN':0,
    'OAK':0
}

In [183]:
print(scores)

{'CAR': 0, 'TB': 0, 'ATL': 0, 'NO': 0, 'IND': 0, 'HOU': 0, 'JAX': 0, 'TEN': 0, 'WAS': 0, 'DAL': 0, 'PHI': 0, 'NYG': 0, 'NE': 0, 'NYJ': 0, 'MIA': 0, 'BUF': 0, 'GB': 0, 'CHI': 0, 'MIN': 0, 'DET': 0, 'BAL': 0, 'PIT': 0, 'CLE': 0, 'CIN': 0, 'SF': 0, 'SEA': 0, 'ARI': 0, 'LAR': 0, 'LAC': 0, 'KC': 0, 'DEN': 0, 'OAK': 0}

In [184]:
week_score_2015 = []
favs_2015 = []
dogs_2015 = []

In [185]:
line_number=1


current_week = 1
#current_year = 2015
for game in season_2015_db.iterrows():
    #print(game[1])
    if game[1][2] != current_week:
        #print(game[1][4])
        week_score_2015.append(scores.copy())
        current_week = game[1][2]
    scores[game[1][3]]+=game[1][4]
    scores[game[1][6]]+=game[1][5]
    if game[1][2] == 21:
        week_score_2015.append(scores.copy())
        break  

print(len(week_score_2015))

21

In [202]:
#print(week_score_2015)

In [187]:
dict_week = 0 
current_week = 1


for game in season_2015_db.iterrows():
    if game[1][2] != current_week:
        current_week = game[1][2]
        dict_week = dict_week + 1
    favs_2015.append(week_score_2015[dict_week][game[1][10]])
    #favs_2015.append(week_score_2015[dict_week][game[1][12]])
    print(game[1][10])
    dogs_2015.append(week_score_2015[dict_week][game[1][11]])
    #print(game[1][11])

NE
ARI
IND
GB
DAL
DEN
KC
CAR
NYJ
OAK
LAC
SEA
TB
MIA
PHI
MIN
KC
BUF
CAR
ARI
CIN
TEN
GB
MIA
MIN
NO
NYG
BAL
PHI
PIT
LAR
IND
NYG
ARI
BAL
CAR
CLE
DEN
HOU
MIA
MIN
NE
NYJ
SEA
LAR
IND
GB
BAL
ARI
ATL
BUF
OAK
CIN
DEN
IND
NYJ
NO
LAC
GB
CAR
PHI
SEA
HOU
ATL
BAL
CIN
NE
ARI
GB
KC
NYG
DEN
PHI
TB
BUF
LAC
ATL
CIN
DEN
DET
GB
NE
JAX
MIN
NYJ
ARI
BAL
SEA
TEN
PHI
SEA
CAR
DET
IND
BUF
KC
MIA
NE
NYG
LAC
LAR
ATL
WAS
ARI
NE
ATL
BAL
MIN
ARI
SEA
GB
HOU
DET
NO
NYJ
LAR
CAR
CIN
BUF
GB
PHI
DEN
MIN
NE
NO
NYJ
PIT
ATL
NYG
LAC
NYJ
BAL
DEN
GB
NE
OAK
PHI
PIT
SEA
LAR
DAL
CAR
NO
CIN
JAX
ARI
ATL
BAL
CAR
DEN
OAK
NYJ
DAL
PHI
KC
SEA
NE
CAR
DET
GB
ATL
CIN
NE
HOU
IND
JAX
KC
NYJ
ARI
SEA
OAK
NYG
CLE
GB
BUF
CHI
CIN
MIA
SEA
NE
CAR
NYJ
KC
PIT
DEN
ARI
ATL
TEN
WAS
ARI
SEA
CAR
CHI
CIN
CLE
DEN
GB
NE
JAX
KC
NYJ
PHI
DET
TB
NYG
LAR
NYJ
KC
IND
JAX
MIN
NE
CAR
GB
ARI
PIT
LAC
CIN
SEA
BUF
NO
OAK
PHI
ARI
CAR
PIT
BUF
DET
KC
MIA
MIN
NO
NE
SEA
TB
HOU
DEN
ARI
ATL
NYJ
CAR
DET
CIN
PIT
DAL
DEN
GB
HOU
IND
KC
NE
NYG
LAR
PIT
KC
SEA
WAS
ARI
NE
CAR
DEN
CAR
NE
CAR

In [203]:
#print(dogs_2015)

In [190]:
season_2015_db['season_total_points_for _favorite'] = favs_2015

C:\Users\kylem\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [198]:
season_2015_db['season_total_points_for _underdog'] = dogs_2015

C:\Users\kylem\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [ ]:
#2016

In [201]:
scores = {
    "CAR":0,
    "TB":0,
    'ATL':0,
    'NO':0,
    'IND':0,
    'HOU':0,
    'JAX':0,
    'TEN':0,
    'WAS':0,
    'DAL':0,
    'PHI':0,
    'NYG':0,
    'NE':0,
    'NYJ':0,
    'MIA':0,
    'BUF':0,
    'GB':0,
    'CHI':0,
    'MIN':0,
    'DET':0,
    'BAL':0,
    'PIT':0,
    'CLE':0,
    'CIN':0,
    'SF':0,
    'SEA':0,
    'ARI':0,
    'LAR':0,
    'LAC':0,
    'KC':0,
    'DEN':0,
    'OAK':0
}

In [204]:
week_score_2016 = []
favs_2016 = []
dogs_2016 = []

In [205]:
current_week = 1
for game in season_2016_db.iterrows():
    #print(game[1])
    if game[1][2] != current_week:
        #print(game[1][4])
        week_score_2016.append(scores.copy())
        current_week = game[1][2]
    scores[game[1][3]]+=game[1][4]
    scores[game[1][6]]+=game[1][5]
    if game[1][2] == 21:
        week_score_2016.append(scores.copy())
        break

In [206]:
dict_week = 0 
current_week = 1


for game in season_2016_db.iterrows():
    if game[1][2] != current_week:
        current_week = game[1][2]
        dict_week = dict_week + 1
    favs_2016.append(week_score_2016[dict_week][game[1][10]])
    #favs_2015.append(week_score_2015[dict_week][game[1][12]])
    print(game[1][10])
    dogs_2015.append(week_score_2016[dict_week][game[1][11]])
    #print(game[1][11])

CAR
ARI
ATL
BAL
NYG
HOU
IND
GB
KC
NO
CIN
PHI
SEA
MIN
LAR
PIT
ARI
CAR
BAL
DEN
DET
HOU
SEA
GB
NE
NYG
OAK
PIT
LAC
WAS
CHI
NE
ARI
CAR
CIN
DAL
GB
IND
BAL
KC
MIA
NYG
PIT
SEA
TB
OAK
NO
CIN
ARI
CAR
BAL
DET
HOU
IND
NE
SEA
PIT
LAC
DAL
DEN
WAS
MIN
ARI
BAL
NE
CIN
DEN
PHI
GB
IND
BUF
MIA
MIN
OAK
PIT
CAR
DEN
BUF
CHI
DET
GB
HOU
PIT
NE
CAR
NYG
KC
SEA
TEN
PHI
ARI
GB
ARI
ATL
CIN
WAS
JAX
KC
NYG
BUF
NYJ
MIN
NE
SF
TEN
DEN
TEN
ATL
NE
CAR
CIN
NYJ
DAL
DEN
HOU
KC
SEA
TB
MIN
ATL
PIT
DAL
GB
KC
CAR
MIA
MIN
NYG
OAK
LAC
NO
SEA
BAL
ARI
CAR
JAX
NE
NO
LAR
PHI
PIT
LAC
CHI
GB
WAS
CAR
CIN
PIT
DAL
DET
IND
KC
MIA
MIN
NYG
NE
SEA
WAS
OAK
DAL
DET
PIT
ATL
BAL
BUF
TEN
NYG
DEN
LAC
MIA
NO
NE
OAK
SEA
PHI
DAL
ARI
ATL
BAL
SF
CIN
GB
DEN
NE
NO
OAK
PIT
LAC
SEA
NYJ
KC
PIT
CAR
CIN
DET
SEA
IND
MIN
ATL
ARI
DAL
WAS
SF
TB
TEN
NE
SEA
MIA
ARI
ATL
BAL
BUF
GB
PIT
DAL
NE
HOU
KC
MIN
NYG
OAK
WAS
PHI
BUF
ATL
WAS
LAC
GB
HOU
TEN
LAR
NE
NO
OAK
SEA
KC
PIT
DAL
ATL
BAL
DEN
GB
IND
ARI
NE
MIN
BUF
PHI
PIT
KC
SEA
TB
TEN
WAS
HOU
SEA
GB
PIT
ATL
NE
DAL
KC
ATL
NE
NE

In [209]:
season_2016_db['season_total_points_for _favorite'] = favs_2016
#season_2016_db['season_total_points_for _underdog'] = dogs_2016

C:\Users\kylem\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [210]:
season_2016_db.tail()

,schedule_date,schedule_season,schedule_week,team_home,score_home,score_away,team_away,spread_favorite,home_win,away_win,favorite,underdog,score_favorite,score_underdog,season_total_points_for _favorite,season_total_points_against_favorite,season_total_points_for _underdog,season_total_points_against_underdog,win_percentage_favorite,win_percentage_underdog
524,1/15/2017,2016,19,DAL,31,34,GB,-5.5,0,1,DAL,GB,31,34,452,0,0,0,0,0
525,1/15/2017,2016,19,KC,16,18,PIT,-2.5,0,1,KC,PIT,16,18,405,0,447,0,0,0
526,1/22/2017,2016,20,ATL,44,21,GB,-6.5,1,0,ATL,GB,44,21,620,0,0,0,0,0
527,1/22/2017,2016,20,NE,36,17,PIT,-5.5,1,0,NE,PIT,36,17,511,0,464,0,0,0
528,2/5/2017,2016,21,NE,34,28,ATL,-3.0,1,0,NE,ATL,34,28,545,0,0,0,0,0